### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by Furglitch** [CollinHeist/TPDbCollectionMaker#5]
After installing poetry through pipx, cloning the git repo, and running the `-h` command, I was getting the following

```
PS C:\Users\Sam\desktop> git clone https://github.com/CollinHeist/TPDbCollectionMaker/
PS C:\Users\Sam\desktop> cd TPDbCollectionMaker
PS C:\Users\Sam\desktop\TPDbCollectionMaker> poetry run python main.py -h
Missing required packages - execute "pipenv install"
```

Took me a minute to realize that I needed to use `poetry install` rather than `pipenv install`. Afterwards it runs just fine.
It might be a good idea to add that to step 3 of the installation process, after `cd`.

**Comment by CollinHeist** [comment]
@Furglitch Thanks! Good catch. I just recently swapped from pipenv to poetry. I updated the instructions and the log message.
